package net.slimelabs.slslite.lobby;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;
import java.util.Map;
import net.slimelabs.slslite.config.ForwardingConfig;
import net.slimelabs.slslite.config.ForwardingMode;
import net.slimelabs.slslite.config.SLSLimboConfig;
import net.slimelabs.slslite.io.BoundedFileReader;
import net.slimelabs.slslite.io.ConfinedFiles;

public final class SLSLimboInstaller {

  public static final String NANOLIMBO_VERSION = "1.13.0";
  public static final String NANOLIMBO_COMMIT = "d192d57d1d4a5fdc7b87643f453d82cb7b9b4242";
  public static final String RUNTIME_SHA256 =
      "4811d42364287913c6ef601016f77049989d875d4741f7ce4c2b8d5364106de1";

  private static final String RESOURCE = "/limbo/nanolimbo-" + NANOLIMBO_VERSION + ".jar";
  private static final String RUNTIME_FILE = "nanolimbo-" + NANOLIMBO_VERSION + ".jar";
  private static final int MAX_RUNTIME_BYTES = 32 * 1024 * 1024;
  private static final int MAX_SECRET_BYTES = 64 * 1024;
  private static final int MAX_SETTINGS_BYTES = 64 * 1024;

  private final Path runtimeDirectory;

  public SLSLimboInstaller(Path dataDirectory) {
    runtimeDirectory = dataDirectory.toAbsolutePath().normalize().resolve("sls-limbo");
  }

  public SLSLimboInstallation install(int port, ForwardingConfig forwarding, int advertisedProtocol)
      throws IOException {
    ConfinedFiles.ensureDirectory(runtimeDirectory);
    Path runtime = runtimeDirectory.resolve(RUNTIME_FILE);
    if (!Files.isRegularFile(runtime, LinkOption.NOFOLLOW_LINKS)
        || Files.isSymbolicLink(runtime)
        || !RUNTIME_SHA256.equalsIgnoreCase(sha256(runtime))) {
      extractRuntime(runtime);
    }
    if (!RUNTIME_SHA256.equalsIgnoreCase(sha256(runtime))) {
      throw new IOException("Bundled SLS-Limbo checksum verification failed");
    }
    Map<Integer, String> supportedProtocols = SLSLimboProtocolCatalog.inspect(runtime);
    if (advertisedProtocol != -1 && !supportedProtocols.containsKey(advertisedProtocol)) {
      throw new IOException(
          "SLS-Limbo advertised protocol "
              + advertisedProtocol
              + " is not supported by bundled NanoLimbo "
              + NANOLIMBO_VERSION);
    }
    if (advertisedProtocol != -1 && advertisedProtocol < SLSLimboConfig.MINIMUM_FIXED_PROTOCOL) {
      throw new IOException(
          "SLS-Limbo fixed protocol must be at least "
              + SLSLimboConfig.MINIMUM_FIXED_PROTOCOL
              + " because older NanoLimbo heightmaps cannot be "
              + "safely translated across Minecraft 1.21.5");
    }

    String forwardingType = forwarding.mode() == ForwardingMode.MODERN ? "MODERN" : "NONE";
    String forwardingSecret = "<UNUSED>";
    if (forwarding.mode() == ForwardingMode.MODERN) {
      if (!Files.isRegularFile(forwarding.secretFile(), LinkOption.NOFOLLOW_LINKS)
          || Files.isSymbolicLink(forwarding.secretFile())) {
        throw new IOException(
            "Velocity forwarding secret does not exist: " + forwarding.secretFile());
      }
      try (InputStream secret =
          BoundedFileReader.openNoFollow(forwarding.secretFile(), MAX_SECRET_BYTES)) {
        ConfinedFiles.atomicCopy(runtimeDirectory, "forwarding.secret", secret, MAX_SECRET_BYTES);
      }
      forwardingSecret = "@forwarding.secret";
    }
    ConfinedFiles.atomicWrite(
        runtimeDirectory,
        "settings.yml",
        settings(port, forwardingType, forwardingSecret, advertisedProtocol)
            .getBytes(java.nio.charset.StandardCharsets.UTF_8),
        MAX_SETTINGS_BYTES);
    return new SLSLimboInstallation(runtimeDirectory, runtime);
  }

  private void extractRuntime(Path destination) throws IOException {
    try (InputStream input = getClass().getResourceAsStream(RESOURCE)) {
      if (input == null) {
        throw new IOException("Bundled SLS-Limbo resource is missing");
      }
      if (!destination.equals(runtimeDirectory.resolve(RUNTIME_FILE))) {
        throw new IOException("SLS-Limbo runtime target changed unexpectedly");
      }
      ConfinedFiles.atomicCopy(runtimeDirectory, RUNTIME_FILE, input, MAX_RUNTIME_BYTES);
    }
  }

  private static String settings(
      int port, String forwardingType, String forwardingSecret, int advertisedProtocol) {
    return """
                # Generated by SLS-LITE. Changes are replaced on proxy startup.
                bind:
                  ip: "127.0.0.1"
                  port: %d
                maxPlayers: 100
                ping:
                  description: "<gold>SLS-Limbo"
                  version: "<gold>SLS-LITE"
                  protocol: %d
                dimension: THE_END
                playerList:
                  enable: false
                  username: "SLS-LITE"
                headerAndFooter:
                  enable: false
                  header: ""
                  footer: ""
                gameMode: 3
                secureProfile: false
                brandName:
                  enable: true
                  content: "<gold>SLS-Limbo"
                joinMessage:
                  enable: true
                  text: "<yellow>You are in SLS-Limbo while your destination gets ready."
                bossBar:
                  enable: true
                  text: "<yellow>Waiting for your destination..."
                  health: 1.0
                  color: YELLOW
                  division: SOLID
                title:
                  enable: true
                  title: "<gold>SLS-LITE"
                  subtitle: "<yellow>SLS-Limbo"
                  fadeIn: 10
                  stay: 100
                  fadeOut: 10
                infoForwarding:
                  type: %s
                  secret: "%s"
                  tokens: []
                readTimeout: 30000
                logPlayersIp: false
                debugLevel: 2
                netty:
                  transportType: NIO
                  threads:
                    bossGroup: 1
                    workerGroup: 2
                traffic:
                  enable: true
                  maxPacketSize: 8192
                  interval: 7.0
                  maxPacketRate: 500.0
                  maxPacketBytesRate: 4096.0
                """
        .formatted(port, advertisedProtocol, forwardingType, forwardingSecret);
  }

  private static String sha256(Path path) throws IOException {
    try {
      MessageDigest digest = MessageDigest.getInstance("SHA-256");
      try (InputStream input = BoundedFileReader.openNoFollow(path, MAX_RUNTIME_BYTES)) {
        byte[] buffer = new byte[8192];
        int read;
        while ((read = input.read(buffer)) != -1) {
          digest.update(buffer, 0, read);
        }
      }
      return HexFormat.of().formatHex(digest.digest());
    } catch (NoSuchAlgorithmException exception) {
      throw new IllegalStateException("SHA-256 is unavailable", exception);
    }
  }

  public record SLSLimboInstallation(Path workingDirectory, Path runtimeJar) {}
}
