package net.slimelabs.slslite.api;

/** Versioned features available through this API implementation. */
public enum Capability {
  BLUEPRINT_INSPECTION,
  INSTANCE_INSPECTION,
  INSTANCE_START,
  INSTANCE_STOP,
  INSTANCE_DELETE,
  PLAYER_QUEUE,
  MATCHMAKING_EVENTS,
  INSTANCE_FAILURE_EVENTS,
  CATALOG_RELOAD_EVENTS,
  LOBBY_STATUS_EVENTS,
  SOFTWARE_INSTALLATION_EVENTS,
  RECONCILIATION_EVENTS,
  API_SHUTDOWN_EVENTS,
  DIAGNOSTICS,
  LIFECYCLE_EVENTS
}
